baseURL = 'https://bh90210.github.io/mlsic/'
languageCode = 'en-us'
title = 'Mlsic blog'
theme = 'hugo-book'
[permalinks]
  [permalinks.page]
    docs = '/blog/:slug/'
  [permalinks.section]
    posts = '/live/'
    docs = '/blog/'

