baseURL = 'https://bh90210.github.io/mlsic/'
languageCode = 'en-us'
title = 'Mlsic blog'
theme = 'hugo-book'
[permalinks]
  [permalinks.page]
    docs = '/:slug/'
  [permalinks.section]
    docs = '/:slug/'
[markup.goldmark.renderer]
  unsafe= true